"""Add student_id to User

Revision ID: 3cdaeb8d5bb8
Revises: 
Create Date: 2025-07-04 14:15:53.505059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cdaeb8d5bb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint("uq_user_student_id", ['student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_student_id", type_='unique')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
